name: Setup Node project
description: Setup Node.js, cache dependencies, and install packages

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v7.0.0
      with:
        node-version: 24.x
        cache: npm
    - name: Cache dependencies
      uses: actions/cache@v6.1.0
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      shell: bash
      run: |
        npm config set engine-strict true
        npm ci
