name: Setup Node project
description: Setup Node.js, cache npm packages, and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v7.0.0
      with:
        node-version: 24.x
        cache: npm
    - name: Install dependencies
      shell: bash
      run: |
        npm config set engine-strict true
        npm ci
