version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
    assignees:
      - kennethbigler
    labels:
      - dependencies
    groups:
      lint:
        patterns:
          - "@eslint/*"
          - "@typescript-eslint/*"
          - eslint*
          - gts
      mui:
        patterns:
          - "@mui/*"
          - "@emotion/*"
      highcharts:
        patterns:
          - highcharts
          - "@highcharts/*"
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
          - "@testing-library/*"
      vite:
        patterns:
          - vite
          - vitest
          - "@vitejs/plugin-react"
          - "@vitest/coverage-v8"
          - jsdom
      cicd:
        patterns:
          - knip
          - "@lhci/cli"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
    assignees:
      - kennethbigler
    labels:
      - dependencies
