# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
reviews:
  profile: assertive
  request_changes_workflow: true
  path_filters:
    - "!docs/**"
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"
    ignore_usernames:
      - "dependabot[bot]"
