#!/bin/bash

echo -e "\n--------------------\n Building react-home \n--------------------\n"
rm index.html
cp -r build/index.html ./
rm -rf ./static
mv build/* ./
echo -e "Success \n--------------------\n"
