import { BotCRole } from "../jotai/botc-atom";

export interface BotCScript {
  townsfolk: BotCRole[];
  outsiders: BotCRole[];
  minions: BotCRole[];
  demons: BotCRole[];
  travelers: BotCRole[];
}

// latest characters found here: https://wiki.bloodontheclocktower.com/Changelog
interface BotCRoleRef {
  [key: string]: BotCRole;
}

const townsfolk: BotCRoleRef = {
  acrobat: { name: "Acrobat", icon: "🤸", alignment: "info" },
  alchemist: { name: "Alchemist", icon: "⚗️", alignment: "info" },
  alsaahir: { name: "Alsaahir", icon: "🚬", alignment: "info" },
  amnesiac: { name: "Amnesiac", icon: "❔", alignment: "info" },
  artist: { name: "Artist", icon: "🎨", alignment: "info" },
  atheist: { name: "Atheist", icon: "🪐", alignment: "info" },
  balloonist: { name: "Balloonist", icon: "🎈", alignment: "info" },
  banshee: { name: "Banshee", icon: "👻", alignment: "info" },
  bountyhunter: { name: "Bounty Hunter", icon: "🕶", alignment: "info" },
  cannibal: { name: "Cannibal", icon: "🍰", alignment: "info" },
  chambermaid: { name: "Chambermaid", icon: "🧹", alignment: "info" },
  chef: { name: "Chef", icon: "👨‍🍳", alignment: "info" },
  choirboy: { name: "Choirboy", icon: "🎼", alignment: "info" },
  clockmaker: { name: "Clockmaker", icon: "🕓", alignment: "info" },
  courtier: { name: "Courtier", icon: "🍸", alignment: "info" },
  cultleader: { name: "Cult Leader", icon: "🪬", alignment: "info" },
  dreamer: { name: "Dreamer", icon: "💭", alignment: "info" },
  empath: { name: "Empath", icon: "🫶", alignment: "info" },
  engineer: { name: "Engineer", icon: "⚙️", alignment: "info" },
  exorcist: { name: "Exorcist", icon: "💼", alignment: "info" },
  farmer: { name: "Farmer", icon: "👨‍🌾", alignment: "info" },
  fisherman: { name: "Fisherman", icon: "🎣", alignment: "info" },
  flowergirl: { name: "Flowergirl", icon: "🌷", alignment: "info" },
  fool: { name: "Fool", icon: "🤡", alignment: "info" },
  fortuneteller: { name: "Fortune Teller", icon: "🔮", alignment: "info" },
  gambler: { name: "Gambler", icon: "🎲", alignment: "info" },
  general: { name: "General", icon: "🎖️", alignment: "info" },
  gossip: { name: "Gossip", icon: "💬", alignment: "info" },
  grandmother: { name: "Grandmother", icon: "👵", alignment: "info" },
  highpriestess: { name: "High Priestess", icon: "🧝‍♀️", alignment: "info" },
  huntsman: { name: "Huntsman", icon: "🏔️", alignment: "info" },
  innkeeper: { name: "Innkeeper", icon: "🛌", alignment: "info" },
  investigator: { name: "Investigator", icon: "🔍", alignment: "info" },
  juggler: { name: "Juggler", icon: "🤹", alignment: "info" },
  king: { name: "King", icon: "🤴", alignment: "info" },
  knight: { name: "Knight", icon: "⚔️", alignment: "info" },
  librarian: { name: "Librarian", icon: "📚", alignment: "info" },
  lycanthrope: { name: "Lycanthrope", icon: "🐺", alignment: "info" },
  magician: { name: "Magician", icon: "🪄", alignment: "info" },
  mathematician: { name: "Mathematician", icon: "🧮", alignment: "info" },
  mayor: { name: "Mayor", icon: "🏛️", alignment: "info" },
  minstrel: { name: "Minstrel", icon: "🪕", alignment: "info" },
  monk: { name: "Monk", icon: "✝️", alignment: "info" },
  nightwatchman: { name: "Nightwatchman", icon: "🌃", alignment: "info" },
  noble: { name: "Noble", icon: "⚜️", alignment: "info" },
  oracle: { name: "Oracle", icon: "𓂀", alignment: "info" },
  pacifist: { name: "Pacifist", icon: "🕊️", alignment: "info" },
  philosopher: { name: "Philosopher", icon: "🤔", alignment: "info" },
  pixie: { name: "Pixie", icon: "🧸", alignment: "info" },
  poppygrower: { name: "Poppy Grower", icon: "🌺", alignment: "info" },
  preacher: { name: "Preacher", icon: "📖", alignment: "info" },
  princess: { name: "Princess", icon: "👸", alignment: "info" },
  professor: { name: "Professor", icon: "⚛️", alignment: "info" },
  ravenkeeper: { name: "Ravenkeeper", icon: "🐦‍⬛", alignment: "info" },
  sage: { name: "Sage", icon: "🕯️", alignment: "info" },
  sailor: { name: "Sailor", icon: "⚓", alignment: "info" },
  savant: { name: "Savant", icon: "🦽", alignment: "info" },
  seamstress: { name: "Seamstress", icon: "🪡", alignment: "info" },
  shugenja: { name: "Shugenja", icon: "⛩️", alignment: "info" },
  slayer: { name: "Slayer", icon: "🏹", alignment: "info" },
  snakecharmer: { name: "Snake Charmer", icon: "🐍", alignment: "info" },
  soldier: { name: "Soldier", icon: "🪖", alignment: "info" },
  steward: { name: "Steward", icon: "📜", alignment: "info" },
  teaLady: { name: "Tea Lady", icon: "🫖", alignment: "info" },
  towncrier: { name: "Town Crier", icon: "🔔", alignment: "info" },
  undertaker: { name: "Undertaker", icon: "🥄", alignment: "info" },
  villageidiot: { name: "Village Idiot", icon: "🍭", alignment: "info" },
  virgin: { name: "Virgin", icon: "🔗", alignment: "info" },
  washerwoman: { name: "Washerwoman", icon: "🧺", alignment: "info" },
};

const outsiders: BotCRoleRef = {
  barber: { name: "Barber", icon: "💈", alignment: "success" },
  butler: { name: "Butler", icon: "👨‍✈️", alignment: "success" },
  damsel: { name: "Damsel", icon: "👠", alignment: "success" },
  drunk: { name: "Drunk", icon: "🍺", alignment: "success" },
  golem: { name: "Golem", icon: "🗿", alignment: "success" },
  goon: { name: "Goon", icon: "🎭", alignment: "success" },
  hatter: { name: "Hatter", icon: "🎩", alignment: "success" },
  heretic: { name: "Heretic", icon: "☦️", alignment: "success" },
  hermit: { name: "Hermit", icon: "🗼", alignment: "success" },
  klutz: { name: "Klutz", icon: "🍌", alignment: "success" },
  lunatic: { name: "Lunatic", icon: "🌀", alignment: "success" },
  moonchild: { name: "Moonchild", icon: "🌙", alignment: "success" },
  mutant: { name: "Mutant", icon: "🎪", alignment: "success" },
  ogre: { name: "Ogre", icon: "🏑", alignment: "success" },
  plagueDoctor: { name: "Plague Doctor", icon: "🩺", alignment: "success" },
  politician: { name: "Politician", icon: "🇺🇸", alignment: "success" },
  puzzlemaster: { name: "Puzzlemaster", icon: "🧩", alignment: "success" },
  recluse: { name: "Recluse", icon: "🕯️", alignment: "success" },
  saint: { name: "Saint", icon: "😇", alignment: "success" },
  snitch: { name: "Snitch", icon: "👄", alignment: "success" },
  sweetheart: { name: "Sweetheart", icon: "🎀", alignment: "success" },
  tinker: { name: "Tinker", icon: "🔧", alignment: "success" },
  zealot: { name: "Zealot", icon: "🍾", alignment: "success" },
};

const minions: BotCRoleRef = {
  assassin: { name: "Assassin", icon: "🗡️", alignment: "error" },
  baron: { name: "Baron", icon: "🎩", alignment: "error" },
  boffin: { name: "Boffin", icon: "⚗️", alignment: "error" },
  boomdandy: { name: "Boomdandy", icon: "💣", alignment: "error" },
  cerenovus: { name: "Cerenovus", icon: "🧠", alignment: "error" },
  devilsAdvocate: { name: "Devil's Advocate", icon: "⚖️", alignment: "error" },
  evilTwin: { name: "Evil Twin", icon: "👯‍♀️", alignment: "error" },
  fearmonger: { name: "Fearmonger", icon: "😱", alignment: "error" },
  goblin: { name: "Goblin", icon: "🫦", alignment: "error" },
  godfather: { name: "Godfather", icon: "🥀", alignment: "error" },
  harpy: { name: "Harpy", icon: "🦅", alignment: "error" },
  marionette: { name: "Marionette", icon: "🎭", alignment: "error" },
  mastermind: { name: "Mastermind", icon: "💺", alignment: "error" },
  mezepheles: { name: "Mezepheles", icon: "🪶", alignment: "error" },
  organGrinder: { name: "Organ Grinder", icon: "🐒", alignment: "error" },
  pitHag: { name: "Pit-Hag", icon: "🥘", alignment: "error" },
  poisoner: { name: "Poisoner", icon: "🧪", alignment: "error" },
  psychopath: { name: "Psychopath", icon: "🪓", alignment: "error" },
  scarletWoman: { name: "Scarlet Woman", icon: "💋", alignment: "error" },
  spy: { name: "Spy", icon: "🤿", alignment: "error" },
  summoner: { name: "Summoner", icon: "⭕️", alignment: "error" },
  vizier: { name: "Vizier", icon: "👑", alignment: "error" },
  widow: { name: "Widow", icon: "🕷️", alignment: "error" },
  witch: { name: "Witch", icon: "🧙‍♀️", alignment: "error" },
  wizard: { name: "Wizard", icon: "🧙‍♂️", alignment: "error" },
  wraith: { name: "Wraith", icon: "👻", alignment: "error" },
  xaan: { name: "Xaan", icon: "♾️", alignment: "error" },
};

const demons: BotCRoleRef = {
  alHadikhia: { name: "Al-Hadikhia", icon: "🎓", alignment: "error" },
  fangGu: { name: "Fang Gu", icon: "🔮", alignment: "error" },
  imp: { name: "Imp", icon: "🔱", alignment: "error" },
  kazali: { name: "Kazali", icon: "😵‍💫", alignment: "error" },
  legion: { name: "Legion", icon: "✋", alignment: "error" },
  leviathan: { name: "Leviathan", icon: "🦕", alignment: "error" },
  lilMonsta: { name: "Lil' Monsta", icon: "🐙", alignment: "error" },
  lleech: { name: "Lleech", icon: "🐛", alignment: "error" },
  lordOfTyphon: { name: "Lord of Typhon", icon: "🐂", alignment: "error" },
  noDashii: { name: "No Dashii", icon: "🦑", alignment: "error" },
  ojo: { name: "Ojo", icon: "👁️", alignment: "error" },
  po: { name: "Po", icon: "🩸", alignment: "error" },
  pukka: { name: "Pukka", icon: "🦂", alignment: "error" },
  riot: { name: "Riot", icon: "🛡️", alignment: "error" },
  shabaloth: { name: "Shabaloth", icon: "👄", alignment: "error" },
  vigormortis: { name: "Vigormortis", icon: "🗝️", alignment: "error" },
  vortox: { name: "Vortox", icon: "🌪️", alignment: "error" },
  yaggababble: { name: "Yaggababble", icon: "💭", alignment: "error" },
  zombuul: { name: "Zombuul", icon: "🧟‍♂️", alignment: "error" },
};

const travelers: BotCRoleRef = {
  apprentice: { name: "Apprentice", icon: "🛠️", alignment: "warning" },
  barista: { name: "Barista", icon: "☕", alignment: "warning" },
  beggar: { name: "Beggar", icon: "🙏", alignment: "warning" },
  bishop: { name: "Bishop", icon: "✝️", alignment: "warning" },
  boneCollector: { name: "Bone Collector", icon: "🦴", alignment: "warning" },
  bureaucrat: { name: "Bureaucrat", icon: "📜", alignment: "warning" },
  butcher: { name: "Butcher", icon: "🔪", alignment: "warning" },
  cacklejack: { name: "Cacklejack", icon: "💡", alignment: "warning" },
  deviant: { name: "Deviant", icon: "📿", alignment: "warning" },
  gangster: { name: "Gangster", icon: "🕵", alignment: "warning" },
  gnome: { name: "Gnome", icon: "🧙", alignment: "warning" },
  gunslinger: { name: "Gunslinger", icon: "🔫", alignment: "warning" },
  harlot: { name: "Harlot", icon: "💃🏼", alignment: "warning" },
  judge: { name: "Judge", icon: "👨‍⚖️", alignment: "warning" },
  matron: { name: "Matron", icon: "🤱", alignment: "warning" },
  scapegoat: { name: "Scapegoat", icon: "🐐", alignment: "warning" },
  thief: { name: "Thief", icon: "🥷🏻", alignment: "warning" },
  voudon: { name: "Voudon", icon: "💀", alignment: "warning" },
};

export const tb: BotCScript = {
  townsfolk: [
    townsfolk.washerwoman,
    townsfolk.monk,
    townsfolk.librarian,
    townsfolk.ravenkeeper,
    townsfolk.investigator,
    townsfolk.virgin,
    townsfolk.chef,
    townsfolk.slayer,
    townsfolk.empath,
    townsfolk.soldier,
    townsfolk.fortuneteller,
    townsfolk.mayor,
    townsfolk.undertaker,
  ],
  outsiders: [
    outsiders.butler,
    outsiders.recluse,
    outsiders.drunk,
    outsiders.saint,
  ],
  minions: [minions.poisoner, minions.baron, minions.spy, minions.scarletWoman],
  demons: [demons.imp],
  travelers: [
    travelers.thief,
    travelers.bureaucrat,
    travelers.gunslinger,
    travelers.scapegoat,
    travelers.beggar,
  ],
};

export const snv: BotCScript = {
  townsfolk: [
    townsfolk.clockmaker,
    townsfolk.savant,
    townsfolk.dreamer,
    townsfolk.seamstress,
    townsfolk.snakecharmer,
    townsfolk.philosopher,
    townsfolk.mathematician,
    townsfolk.artist,
    townsfolk.flowergirl,
    townsfolk.juggler,
    townsfolk.towncrier,
    townsfolk.sage,
    townsfolk.oracle,
  ],
  outsiders: [
    outsiders.mutant,
    outsiders.sweetheart,
    outsiders.barber,
    outsiders.klutz,
  ],
  minions: [minions.witch, minions.pitHag, minions.cerenovus, minions.evilTwin],
  demons: [demons.fangGu, demons.noDashii, demons.vigormortis, demons.vortox],
  travelers: [
    travelers.barista,
    travelers.harlot,
    travelers.butcher,
    travelers.deviant,
    travelers.boneCollector,
    travelers.gangster,
  ],
};

export const bmr: BotCScript = {
  townsfolk: [
    townsfolk.grandmother,
    townsfolk.gossip,
    townsfolk.sailor,
    townsfolk.courtier,
    townsfolk.chambermaid,
    townsfolk.professor,
    townsfolk.exorcist,
    townsfolk.minstrel,
    townsfolk.innkeeper,
    townsfolk.teaLady,
    townsfolk.gambler,
    townsfolk.pacifist,
    townsfolk.fool,
  ],
  outsiders: [
    outsiders.goon,
    outsiders.tinker,
    outsiders.lunatic,
    outsiders.moonchild,
  ],
  minions: [
    minions.godfather,
    minions.assassin,
    minions.devilsAdvocate,
    minions.mastermind,
  ],
  demons: [demons.zombuul, demons.shabaloth, demons.pukka, demons.po],
  travelers: [
    travelers.apprentice,
    travelers.matron,
    travelers.judge,
    travelers.voudon,
    travelers.bishop,
  ],
};

export const swpm: BotCScript = {
  townsfolk: [
    townsfolk.chef,
    townsfolk.amnesiac,
    townsfolk.investigator,
    townsfolk.seamstress,
    townsfolk.librarian,
    townsfolk.philosopher,
    townsfolk.pixie,
    townsfolk.ravenkeeper,
    townsfolk.dreamer,
    townsfolk.cannibal,
    townsfolk.snakecharmer,
    townsfolk.mayor,
    townsfolk.oracle,
  ],
  outsiders: [
    outsiders.recluse,
    outsiders.drunk,
    outsiders.mutant,
    outsiders.lunatic,
  ],
  minions: [
    minions.godfather,
    minions.pitHag,
    minions.spy,
    minions.marionette,
    minions.cerenovus,
  ],
  demons: [demons.imp, demons.fangGu, demons.vigormortis],
  travelers: [],
};

export const other: BotCScript = {
  townsfolk: Object.keys(townsfolk).map((key) => townsfolk[key]),
  outsiders: Object.keys(outsiders).map((key) => outsiders[key]),
  minions: Object.keys(minions).map((key) => minions[key]),
  demons: Object.keys(demons).map((key) => demons[key]),
  travelers: Object.keys(travelers).map((key) => travelers[key]),
};

export const playerDist = [
  "",
  "",
  "",
  "",
  "",
  "3, 0, 1, 1",
  "3, 1, 1, 1",
  "5, 0, 1, 1",
  "5, 1, 1, 1",
  "5, 2, 1, 1",
  "7, 0, 2, 1",
  "7, 1, 2, 1",
  "7, 2, 2, 1",
  "9, 0, 3, 1",
  "9, 1, 3, 1",
  "9, 2, 3, 1",
];
