// list of countries visited, broken down by region
export const NA = [
  'Bahamas',
  'British Virgin Islands',
  'Canada',
  'Cayman Islands',
  'Mexico',
  'U.S. Virgin Islands',
  'United States',
];
export const EU = [
  'Austria',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Gibraltar',
  'Greece',
  'Iceland',
  'Ireland',
  'Italy',
  'Malta',
  'Monaco',
  'Netherlands',
  'Norway',
  'Portugal',
  'Russia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Turkey',
  'United Kingdom',
  'Vatican',
];
