const STR = 'Strength';
const AGI = 'Agility';
const INT = 'Intelligence';

export default [
  { name: 'Abaddon', selected: false, attribute: STR },
  { name: 'Alchemist', selected: false, attribute: STR },
  { name: 'Axe', selected: false, attribute: STR },
  { name: 'Beastmaster', selected: false, attribute: STR },
  { name: 'Brewmaster', selected: false, attribute: STR },
  { name: 'Bristleback', selected: false, attribute: STR },
  { name: 'Centaur Warrunner', selected: false, attribute: STR },
  { name: 'Chaos Knight', selected: false, attribute: STR },
  { name: 'Ancient Apparition', selected: false, attribute: INT },
  { name: 'Anti-mage', selected: false, attribute: AGI },
  { name: 'Arc Warden', selected: false, attribute: AGI },
  { name: 'Bane', selected: false, attribute: INT },
  { name: 'Batrider', selected: false, attribute: INT },
  { name: 'Bloodseeker', selected: false, attribute: AGI },
  { name: 'Bounty Hunter', selected: false, attribute: AGI },
  { name: 'Broodmother', selected: false, attribute: AGI },
  { name: 'Chen', selected: false, attribute: INT },
  { name: 'Clinkz', selected: false, attribute: AGI },
  { name: 'Clockwerk', selected: false, attribute: STR },
  { name: 'Crystal Maiden', selected: false, attribute: INT },
  { name: 'Dark Seer', selected: false, attribute: INT },
  { name: 'Dark Willow', selected: false, attribute: INT },
  { name: 'Dazzle', selected: false, attribute: INT },
  { name: 'Death Prophet', selected: false, attribute: INT },
  { name: 'Disruptor', selected: false, attribute: INT },
  { name: 'Doom', selected: false, attribute: STR },
  { name: 'Dragon Knight', selected: false, attribute: STR },
  { name: 'Drow Ranger', selected: false, attribute: AGI },
  { name: 'Earth Spirit', selected: false, attribute: STR },
  { name: 'Earthshaker', selected: false, attribute: STR },
  { name: 'Elder Titan', selected: false, attribute: STR },
  { name: 'Ember Spirit', selected: false, attribute: AGI },
  { name: 'Enchantress', selected: false, attribute: INT },
  { name: 'Enigma', selected: false, attribute: INT },
  { name: 'Faceless Void', selected: false, attribute: AGI },
  { name: 'Grimstroke', selected: false, attribute: INT },
  { name: 'Gyrocopter', selected: false, attribute: AGI },
  { name: 'Huskar', selected: false, attribute: STR },
  { name: 'Invoker', selected: false, attribute: INT },
  { name: 'Io', selected: false, attribute: STR },
  { name: 'Jakiro', selected: false, attribute: INT },
  { name: 'Juggernaut', selected: false, attribute: AGI },
  { name: 'Keeper of the Light', selected: false, attribute: INT },
  { name: 'Kunkka', selected: false, attribute: STR },
  { name: 'Legion Commander', selected: false, attribute: STR },
  { name: 'Leshrac', selected: false, attribute: INT },
  { name: 'Lich', selected: false, attribute: INT },
  { name: 'Lifestealer', selected: false, attribute: STR },
  { name: 'Lina', selected: false, attribute: INT },
  { name: 'Lion', selected: false, attribute: INT },
  { name: 'Lone Druid', selected: false, attribute: AGI },
  { name: 'Luna', selected: false, attribute: AGI },
  { name: 'Lycan', selected: false, attribute: STR },
  { name: 'Magnus', selected: false, attribute: STR },
  // { name: 'Mars', selected: false, attribute: STR },
  { name: 'Medusa', selected: false, attribute: AGI },
  { name: 'Meepo', selected: false, attribute: AGI },
  { name: 'Mirana', selected: false, attribute: AGI },
  { name: 'Monkey King', selected: false, attribute: AGI },
  { name: 'Morphling', selected: false, attribute: AGI },
  { name: 'Naga Siren', selected: false, attribute: AGI },
  { name: 'Nature\'s Prophet', selected: false, attribute: INT },
  { name: 'Necrophos', selected: false, attribute: INT },
  { name: 'Night Stalker', selected: false, attribute: STR },
  { name: 'Nyx Assassin', selected: false, attribute: AGI },
  { name: 'Ogre Magi', selected: false, attribute: INT },
  { name: 'Omniknight', selected: false, attribute: STR },
  { name: 'Oracle', selected: false, attribute: INT },
  { name: 'Outworld Devourer', selected: false, attribute: INT },
  { name: 'Pangolier', selected: false, attribute: AGI },
  { name: 'Phantom Assassin', selected: false, attribute: AGI },
  { name: 'Phantom Lancer', selected: false, attribute: AGI },
  { name: 'Phoenix', selected: false, attribute: STR },
  { name: 'Puck', selected: false, attribute: INT },
  { name: 'Pudge', selected: false, attribute: STR },
  { name: 'Pugna', selected: false, attribute: INT },
  { name: 'Queen of Pain', selected: false, attribute: INT },
  { name: 'Razor', selected: false, attribute: AGI },
  { name: 'Riki', selected: false, attribute: AGI },
  { name: 'Rubick', selected: false, attribute: INT },
  { name: 'Sand King', selected: false, attribute: STR },
  { name: 'Shadow Demon', selected: false, attribute: INT },
  { name: 'Shadow Fiend', selected: false, attribute: AGI },
  { name: 'Shadow Shaman', selected: false, attribute: INT },
  { name: 'Silencer', selected: false, attribute: INT },
  { name: 'Skywrath Mage', selected: false, attribute: INT },
  { name: 'Slardar', selected: false, attribute: STR },
  { name: 'Slark', selected: false, attribute: AGI },
  { name: 'Sniper', selected: false, attribute: AGI },
  { name: 'Spectre', selected: false, attribute: AGI },
  { name: 'Spirit Breaker', selected: false, attribute: STR },
  { name: 'Storm Spirit', selected: false, attribute: INT },
  { name: 'Sven', selected: false, attribute: STR },
  { name: 'Techies', selected: false, attribute: INT },
  { name: 'Templar Assassin', selected: false, attribute: AGI },
  { name: 'Terrorblade', selected: false, attribute: AGI },
  { name: 'Tidehunter', selected: false, attribute: STR },
  { name: 'Timbersaw', selected: false, attribute: STR },
  { name: 'Tinker', selected: false, attribute: INT },
  { name: 'Tiny', selected: false, attribute: STR },
  { name: 'Treant Protector', selected: false, attribute: STR },
  { name: 'Troll Warlord', selected: false, attribute: AGI },
  { name: 'Tusk', selected: false, attribute: STR },
  { name: 'Underlord', selected: false, attribute: STR },
  { name: 'Undying', selected: false, attribute: STR },
  { name: 'Ursa', selected: false, attribute: AGI },
  { name: 'Vengeful Spirit', selected: false, attribute: AGI },
  { name: 'Venomancer', selected: false, attribute: AGI },
  { name: 'Viper', selected: false, attribute: AGI },
  { name: 'Visage', selected: false, attribute: INT },
  { name: 'Warlock', selected: false, attribute: INT },
  { name: 'Weaver', selected: false, attribute: AGI },
  { name: 'Windranger', selected: false, attribute: INT },
  { name: 'Winter Wyvern', selected: false, attribute: INT },
  { name: 'Witch Doctor', selected: false, attribute: INT },
  { name: 'Wraith King', selected: false, attribute: STR },
  { name: 'Zeus', selected: false, attribute: INT },
];
