import sortBy from 'lodash/sortBy';
import { ATR, DBDota2Hero } from '../store/types';

export type Alphabet = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z';
type DotaHistogram = Record<Alphabet, DBDota2Hero[]>;

export const heroes: DBDota2Hero[] = [
  { name: 'Abaddon', selected: false, attribute: ATR.STR },
  { name: 'Alchemist', selected: false, attribute: ATR.STR },
  { name: 'Axe', selected: false, attribute: ATR.STR },
  { name: 'Beastmaster', selected: false, attribute: ATR.STR },
  { name: 'Brewmaster', selected: false, attribute: ATR.STR },
  { name: 'Bristleback', selected: false, attribute: ATR.STR },
  { name: 'Centaur Warrunner', selected: false, attribute: ATR.STR },
  { name: 'Chaos Knight', selected: false, attribute: ATR.STR },
  { name: 'Ancient Apparition', selected: false, attribute: ATR.INT },
  { name: 'Anti-mage', selected: false, attribute: ATR.AGI },
  { name: 'Arc Warden', selected: false, attribute: ATR.AGI },
  { name: 'Bane', selected: false, attribute: ATR.INT },
  { name: 'Batrider', selected: false, attribute: ATR.INT },
  { name: 'Bloodseeker', selected: false, attribute: ATR.AGI },
  { name: 'Bounty Hunter', selected: false, attribute: ATR.AGI },
  { name: 'Broodmother', selected: false, attribute: ATR.AGI },
  { name: 'Chen', selected: false, attribute: ATR.INT },
  { name: 'Clinkz', selected: false, attribute: ATR.AGI },
  { name: 'Clockwerk', selected: false, attribute: ATR.STR },
  { name: 'Crystal Maiden', selected: false, attribute: ATR.INT },
  { name: 'Dark Seer', selected: false, attribute: ATR.INT },
  { name: 'Dark Willow', selected: false, attribute: ATR.INT },
  { name: 'Dazzle', selected: false, attribute: ATR.INT },
  { name: 'Death Prophet', selected: false, attribute: ATR.INT },
  { name: 'Disruptor', selected: false, attribute: ATR.INT },
  { name: 'Doom', selected: false, attribute: ATR.STR },
  { name: 'Dragon Knight', selected: false, attribute: ATR.STR },
  { name: 'Drow Ranger', selected: false, attribute: ATR.AGI },
  { name: 'Earth Spirit', selected: false, attribute: ATR.STR },
  { name: 'Earthshaker', selected: false, attribute: ATR.STR },
  { name: 'Elder Titan', selected: false, attribute: ATR.STR },
  { name: 'Ember Spirit', selected: false, attribute: ATR.AGI },
  { name: 'Enchantress', selected: false, attribute: ATR.INT },
  { name: 'Enigma', selected: false, attribute: ATR.INT },
  { name: 'Faceless Void', selected: false, attribute: ATR.AGI },
  { name: 'Grimstroke', selected: false, attribute: ATR.INT },
  { name: 'Gyrocopter', selected: false, attribute: ATR.AGI },
  { name: 'Huskar', selected: false, attribute: ATR.STR },
  { name: 'Invoker', selected: false, attribute: ATR.INT },
  { name: 'Io', selected: false, attribute: ATR.STR },
  { name: 'Jakiro', selected: false, attribute: ATR.INT },
  { name: 'Juggernaut', selected: false, attribute: ATR.AGI },
  { name: 'Keeper of the Light', selected: false, attribute: ATR.INT },
  { name: 'Kunkka', selected: false, attribute: ATR.STR },
  { name: 'Legion Commander', selected: false, attribute: ATR.STR },
  { name: 'Leshrac', selected: false, attribute: ATR.INT },
  { name: 'Lich', selected: false, attribute: ATR.INT },
  { name: 'Lifestealer', selected: false, attribute: ATR.STR },
  { name: 'Lina', selected: false, attribute: ATR.INT },
  { name: 'Lion', selected: false, attribute: ATR.INT },
  { name: 'Lone Druid', selected: false, attribute: ATR.AGI },
  { name: 'Luna', selected: false, attribute: ATR.AGI },
  { name: 'Lycan', selected: false, attribute: ATR.STR },
  { name: 'Magnus', selected: false, attribute: ATR.STR },
  // { name: 'Mars', selected: false, attribute: ATR.STR },
  { name: 'Medusa', selected: false, attribute: ATR.AGI },
  { name: 'Meepo', selected: false, attribute: ATR.AGI },
  { name: 'Mirana', selected: false, attribute: ATR.AGI },
  { name: 'Monkey King', selected: false, attribute: ATR.AGI },
  { name: 'Morphling', selected: false, attribute: ATR.AGI },
  { name: 'Naga Siren', selected: false, attribute: ATR.AGI },
  { name: 'Nature\'s Prophet', selected: false, attribute: ATR.INT },
  { name: 'Necrophos', selected: false, attribute: ATR.INT },
  { name: 'Night Stalker', selected: false, attribute: ATR.STR },
  { name: 'Nyx Assassin', selected: false, attribute: ATR.AGI },
  { name: 'Ogre Magi', selected: false, attribute: ATR.INT },
  { name: 'Omniknight', selected: false, attribute: ATR.STR },
  { name: 'Oracle', selected: false, attribute: ATR.INT },
  { name: 'Outworld Devourer', selected: false, attribute: ATR.INT },
  { name: 'Pangolier', selected: false, attribute: ATR.AGI },
  { name: 'Phantom Assassin', selected: false, attribute: ATR.AGI },
  { name: 'Phantom Lancer', selected: false, attribute: ATR.AGI },
  { name: 'Phoenix', selected: false, attribute: ATR.STR },
  { name: 'Puck', selected: false, attribute: ATR.INT },
  { name: 'Pudge', selected: false, attribute: ATR.STR },
  { name: 'Pugna', selected: false, attribute: ATR.INT },
  { name: 'Queen of Pain', selected: false, attribute: ATR.INT },
  { name: 'Razor', selected: false, attribute: ATR.AGI },
  { name: 'Riki', selected: false, attribute: ATR.AGI },
  { name: 'Rubick', selected: false, attribute: ATR.INT },
  { name: 'Sand King', selected: false, attribute: ATR.STR },
  { name: 'Shadow Demon', selected: false, attribute: ATR.INT },
  { name: 'Shadow Fiend', selected: false, attribute: ATR.AGI },
  { name: 'Shadow Shaman', selected: false, attribute: ATR.INT },
  { name: 'Silencer', selected: false, attribute: ATR.INT },
  { name: 'Skywrath Mage', selected: false, attribute: ATR.INT },
  { name: 'Slardar', selected: false, attribute: ATR.STR },
  { name: 'Slark', selected: false, attribute: ATR.AGI },
  { name: 'Sniper', selected: false, attribute: ATR.AGI },
  { name: 'Spectre', selected: false, attribute: ATR.AGI },
  { name: 'Spirit Breaker', selected: false, attribute: ATR.STR },
  { name: 'Storm Spirit', selected: false, attribute: ATR.INT },
  { name: 'Sven', selected: false, attribute: ATR.STR },
  { name: 'Techies', selected: false, attribute: ATR.INT },
  { name: 'Templar Assassin', selected: false, attribute: ATR.AGI },
  { name: 'Terrorblade', selected: false, attribute: ATR.AGI },
  { name: 'Tidehunter', selected: false, attribute: ATR.STR },
  { name: 'Timbersaw', selected: false, attribute: ATR.STR },
  { name: 'Tinker', selected: false, attribute: ATR.INT },
  { name: 'Tiny', selected: false, attribute: ATR.STR },
  { name: 'Treant Protector', selected: false, attribute: ATR.STR },
  { name: 'Troll Warlord', selected: false, attribute: ATR.AGI },
  { name: 'Tusk', selected: false, attribute: ATR.STR },
  { name: 'Underlord', selected: false, attribute: ATR.STR },
  { name: 'Undying', selected: false, attribute: ATR.STR },
  { name: 'Ursa', selected: false, attribute: ATR.AGI },
  { name: 'Vengeful Spirit', selected: false, attribute: ATR.AGI },
  { name: 'Venomancer', selected: false, attribute: ATR.AGI },
  { name: 'Viper', selected: false, attribute: ATR.AGI },
  { name: 'Visage', selected: false, attribute: ATR.INT },
  { name: 'Warlock', selected: false, attribute: ATR.INT },
  { name: 'Weaver', selected: false, attribute: ATR.AGI },
  { name: 'Windranger', selected: false, attribute: ATR.INT },
  { name: 'Winter Wyvern', selected: false, attribute: ATR.INT },
  { name: 'Witch Doctor', selected: false, attribute: ATR.INT },
  { name: 'Wraith King', selected: false, attribute: ATR.STR },
  { name: 'Zeus', selected: false, attribute: ATR.INT },
];

const orderedHeroes = sortBy(heroes, 'name').reduce(
  (acc: DotaHistogram, hero: DBDota2Hero) => {
    const key = hero.name[0] as Alphabet;

    if (!acc[key]) {
      acc[key] = [hero];
    } else {
      acc[key].push(hero);
    }

    return acc;
  },
  {} as DotaHistogram,
);

export const resetHeroesStatuses = (): void => {
  heroes.forEach((hero: DBDota2Hero): void => { hero.selected = false; });
};

export default orderedHeroes;
