export default [
  {
    make: "Porsche",
    model: "Carrera GT",
    styling: 9,
    acceleration: 9,
    handling: 10,
    coolFactor: 10,
    importance: 10,
    features: 3,
    comfort: 3,
    quality: 9,
    practical: 1,
    value: 8
  },
  {
    make: "Ferrari",
    model: "488 Spider",
    styling: 9,
    acceleration: 9,
    handling: 9,
    coolFactor: 8,
    importance: 8,
    features: 7,
    comfort: 4,
    quality: 8,
    practical: 3,
    value: 6
  },
  {
    make: "Lamborghini",
    model: "Huracan",
    styling: 8,
    acceleration: 10,
    handling: 10,
    coolFactor: 8,
    importance: 8,
    features: 6,
    comfort: 4,
    quality: 8,
    practical: 2,
    value: 7
  },
  {
    make: "Bentley",
    model: "Bentayga",
    styling: 5,
    acceleration: 8,
    handling: 6,
    coolFactor: 6,
    importance: 7,
    features: 7,
    comfort: 9,
    quality: 9,
    practical: 8,
    value: 5
  },
  {
    make: "Audi",
    model: "2017 R8 V10 Plus",
    styling: 7,
    acceleration: 10,
    handling: 8,
    coolFactor: 8,
    importance: 7,
    features: 8,
    comfort: 5,
    quality: 8,
    practical: 2,
    value: 7
  },
  {
    make: "Tesla",
    model: "Model X 90D",
    styling: 5,
    acceleration: 6,
    handling: 5,
    coolFactor: 8,
    importance: 7,
    features: 10,
    comfort: 7,
    quality: 4,
    practical: 10,
    value: 7
  },
  {
    make: "Ford",
    model: "2005 Ford GT",
    styling: 10,
    acceleration: 8,
    handling: 9,
    coolFactor: 9,
    importance: 9,
    features: 3,
    comfort: 4,
    quality: 7,
    practical: 1,
    value: 8
  },
  {
    make: "Rolls Royce",
    model: "Wraith",
    styling: 6,
    acceleration: 7,
    handling: 6,
    coolFactor: 8,
    importance: 6,
    features: 9,
    comfort: 10,
    quality: 8,
    practical: 4,
    value: 4
  },
  {
    make: "Ford",
    model: "2017 Raptor",
    styling: 7,
    acceleration: 5,
    handling: 4,
    coolFactor: 7,
    importance: 6,
    features: 8,
    comfort: 7,
    quality: 7,
    practical: 8,
    value: 8
  },
  {
    make: "Ferrari",
    model: "GTC4Lusso",
    styling: 5,
    acceleration: 9,
    handling: 7,
    coolFactor: 8,
    importance: 7,
    features: 7,
    comfort: 6,
    quality: 8,
    practical: 6,
    value: 4
  },
  {
    make: "Audi",
    model: "2014 Audi R8",
    styling: 8,
    acceleration: 7,
    handling: 8,
    coolFactor: 7,
    importance: 8,
    features: 5,
    comfort: 6,
    quality: 8,
    practical: 2,
    value: 8
  },
  {
    make: "Aston Martin",
    model: "DB11",
    styling: 9,
    acceleration: 8,
    handling: 7,
    coolFactor: 8,
    importance: 7,
    features: 7,
    comfort: 6,
    quality: 8,
    practical: 3,
    value: 3
  },
  {
    make: "Ford",
    model: "2017 Ford GT",
    styling: 8,
    acceleration: 10,
    handling: 10,
    coolFactor: 10,
    importance: 9,
    features: 5,
    comfort: 2,
    quality: 6,
    practical: 1,
    value: 5
  },
  {
    make: "Bentley",
    model: "Conti Supersports",
    styling: 6,
    acceleration: 9,
    handling: 7,
    coolFactor: 7,
    importance: 6,
    features: 6,
    comfort: 8,
    quality: 8,
    practical: 4,
    value: 5
  },
  {
    make: "Porsche",
    model: "911R",
    styling: 8,
    acceleration: 8,
    handling: 9,
    coolFactor: 8,
    importance: 9,
    features: 6,
    comfort: 4,
    quality: 9,
    practical: 2,
    value: 3
  },
  {
    make: "Lexus",
    model: "Lexus LFA",
    styling: 6,
    acceleration: 8,
    handling: 8,
    coolFactor: 9,
    importance: 9,
    features: 6,
    comfort: 5,
    quality: 9,
    practical: 2,
    value: 4
  },
  {
    make: "Porsche",
    model: "997 Turbo",
    styling: 7,
    acceleration: 8,
    handling: 7,
    coolFactor: 7,
    importance: 6,
    features: 5,
    comfort: 6,
    quality: 8,
    practical: 3,
    value: 8
  },
  {
    make: "McLaren",
    model: "SLR",
    styling: 7,
    acceleration: 9,
    handling: 6,
    coolFactor: 9,
    importance: 9,
    features: 4,
    comfort: 6,
    quality: 6,
    practical: 3,
    value: 5
  },
  {
    make: "Lamborghini",
    model: "Aventador SV",
    styling: 7,
    acceleration: 10,
    handling: 8,
    coolFactor: 9,
    importance: 8,
    features: 6,
    comfort: 3,
    quality: 7,
    practical: 2,
    value: 4
  },
  {
    make: "Mercedes",
    model: "R63 AMG",
    styling: 4,
    acceleration: 7,
    handling: 5,
    coolFactor: 8,
    importance: 6,
    features: 6,
    comfort: 7,
    quality: 6,
    practical: 10,
    value: 5
  },
  {
    make: "BMW",
    model: "BMW M5 (E39)",
    styling: 8,
    acceleration: 6,
    handling: 6,
    coolFactor: 7,
    importance: 7,
    features: 4,
    comfort: 7,
    quality: 7,
    practical: 5,
    value: 7
  },
  {
    make: "Lamborghini",
    model: "Diablo 6.0",
    styling: 9,
    acceleration: 9,
    handling: 7,
    coolFactor: 9,
    importance: 8,
    features: 3,
    comfort: 3,
    quality: 4,
    practical: 2,
    value: 7
  },
  {
    make: "Ferrari",
    model: "430 Scuderia",
    styling: 8,
    acceleration: 9,
    handling: 9,
    coolFactor: 8,
    importance: 8,
    features: 2,
    comfort: 2,
    quality: 7,
    practical: 2,
    value: 7
  },
  {
    make: "Ferrari",
    model: "F40",
    styling: 10,
    acceleration: 8,
    handling: 9,
    coolFactor: 10,
    importance: 10,
    features: 1,
    comfort: 2,
    quality: 4,
    practical: 1,
    value: 7
  },
  {
    make: "Chevrolet",
    model: "Bolt",
    styling: 5,
    acceleration: 3,
    handling: 4,
    coolFactor: 6,
    importance: 7,
    features: 7,
    comfort: 5,
    quality: 5,
    practical: 9,
    value: 8
  },
  {
    make: "Ferrari",
    model: "Ferrari F355",
    styling: 10,
    acceleration: 6,
    handling: 7,
    coolFactor: 8,
    importance: 8,
    features: 3,
    comfort: 4,
    quality: 3,
    practical: 3,
    value: 6
  },
  {
    make: "BMW",
    model: "BMW M3 (E46)",
    styling: 7,
    acceleration: 6,
    handling: 7,
    coolFactor: 6,
    importance: 6,
    features: 3,
    comfort: 6,
    quality: 5,
    practical: 4,
    value: 7
  },
  {
    make: "Porsche",
    model: "996 C4S",
    styling: 5,
    acceleration: 6,
    handling: 7,
    coolFactor: 6,
    importance: 6,
    features: 4,
    comfort: 5,
    quality: 5,
    practical: 3,
    value: 9
  },
  {
    make: "Porsche",
    model: "928 GTS",
    styling: 7,
    acceleration: 5,
    handling: 6,
    coolFactor: 7,
    importance: 7,
    features: 3,
    comfort: 6,
    quality: 5,
    practical: 4,
    value: 6
  },
  {
    make: "Dodge",
    model: "97 Viper GTS",
    styling: 7,
    acceleration: 7,
    handling: 6,
    coolFactor: 7,
    importance: 7,
    features: 3,
    comfort: 3,
    quality: 4,
    practical: 3,
    value: 7
  },
  {
    make: "Ferrari",
    model: "Ferrari 348",
    styling: 6,
    acceleration: 4,
    handling: 6,
    coolFactor: 7,
    importance: 7,
    features: 3,
    comfort: 4,
    quality: 5,
    practical: 3,
    value: 7
  },
  {
    make: "Rolls Royce",
    model: "Silver Spur",
    styling: 4,
    acceleration: 1,
    handling: 3,
    coolFactor: 6,
    importance: 5,
    features: 3,
    comfort: 10,
    quality: 6,
    practical: 5,
    value: 6
  },
  {
    make: "Lamborghini",
    model: "LM002",
    styling: 5,
    acceleration: 1,
    handling: 4,
    coolFactor: 10,
    importance: 8,
    features: 3,
    comfort: 4,
    quality: 4,
    practical: 4,
    value: 6
  },
  {
    make: "Land Rover",
    model: "06 Range Rover",
    styling: 6,
    acceleration: 1,
    handling: 4,
    coolFactor: 5,
    importance: 4,
    features: 4,
    comfort: 7,
    quality: 4,
    practical: 9,
    value: 5
  },
  {
    make: "Maserati",
    model: "05 Quattroporte",
    styling: 4,
    acceleration: 5,
    handling: 6,
    coolFactor: 6,
    importance: 5,
    features: 4,
    comfort: 5,
    quality: 3,
    practical: 5,
    value: 4
  },
  {
    make: "Cadillac",
    model: "1977 Eldorado",
    styling: 5,
    acceleration: 1,
    handling: 2,
    coolFactor: 7,
    importance: 6,
    features: 2,
    comfort: 8,
    quality: 5,
    practical: 4,
    value: 6
  },
  {
    make: "Plymouth",
    model: "Prowler",
    styling: 6,
    acceleration: 4,
    handling: 5,
    coolFactor: 6,
    importance: 6,
    features: 3,
    comfort: 4,
    quality: 5,
    practical: 1,
    value: 5
  },
  {
    make: "Pontiac",
    model: "Aztek",
    styling: 2,
    acceleration: 1,
    handling: 3,
    coolFactor: 2,
    importance: 7,
    features: 4,
    comfort: 5,
    quality: 4,
    practical: 10,
    value: 5
  },
  {
    make: "Cadillac",
    model: "Cadillac ELR",
    styling: 6,
    acceleration: 1,
    handling: 4,
    coolFactor: 2,
    importance: 3,
    features: 7,
    comfort: 7,
    quality: 6,
    practical: 3,
    value: 2
  },
  {
    make: "Yugo",
    model: "Yugo",
    styling: 3,
    acceleration: 1,
    handling: 2,
    coolFactor: 6,
    importance: 7,
    features: 2,
    comfort: 4,
    quality: 1,
    practical: 4,
    value: 4
  },
  {
    make: "Nissan",
    model: "Murano CC",
    styling: 2,
    acceleration: 1,
    handling: 3,
    coolFactor: 2,
    importance: 3,
    features: 5,
    comfort: 5,
    quality: 5,
    practical: 4,
    value: 3
  },
  {
    make: "Daimler",
    model: "Ferret Tank",
    styling: 6,
    acceleration: 1,
    handling: 1,
    coolFactor: 8,
    importance: 5,
    features: 1,
    comfort: 1,
    quality: 2,
    practical: 1,
    value: 7
  },
  {
    make: "VEB Sachsenring Automobilwerke Zwickau",
    model: "Trabant",
    styling: 2,
    acceleration: 1,
    handling: 1,
    coolFactor: 6,
    importance: 9,
    features: 1,
    comfort: 2,
    quality: 1,
    practical: 4,
    value: 5
  },
  {
    make: "BMW",
    model: "Isetta",
    styling: 5,
    acceleration: 1,
    handling: 1,
    coolFactor: 7,
    importance: 6,
    features: 1,
    comfort: 1,
    quality: 1,
    practical: 1,
    value: 4
  },
  {
    make: "Lexus",
    model: "Lexus LC 500",
    styling: 8,
    acceleration: 6,
    handling: 6,
    coolFactor: 7,
    importance: 7,
    features: 9,
    comfort: 7,
    quality: 10,
    practical: 2,
    value: 6
  }
];

/*
,
{
  make: "",
  model: "",
  styling: ,
  acceleration: ,
  handling: ,
  coolFactor: ,
  importance: ,
  features: ,
  comfort: ,
  quality: ,
  practical: ,
  value:
}
*/
