import {
  red,
  yellow,
  // blue,
  orange,
  green,
  // purple,
  grey,
} from "@mui/material/colors";
import dateObj from "../apis/DateHelper";

const letters = [
  // contains blue
  {
    color: grey[900],
    start: dateObj("2011-9"),
    end: dateObj("2012-6"),
    letter: "E",
    title: "E",
  },
  {
    color: grey[900],
    start: dateObj("2012-9"),
    end: dateObj("2013-2"),
    letter: "M",
    title: "M",
  },
  {
    color: grey[900],
    start: dateObj("2013-2"),
    end: dateObj("2014-8"),
    letter: "S",
    title: "S",
  },
  {
    color: green[500],
    start: dateObj("2015-5"),
    end: dateObj("2015-8"),
    letter: "A",
    title: "A",
  },
  {
    color: green[500],
    start: dateObj("2016-3"),
    end: dateObj("2016-8"),
    letter: "H",
    title: "H",
  },
  {
    color: grey[900],
    start: dateObj("2016-10"),
    end: dateObj("2017-1"),
    letter: "S",
    title: "S",
  },
  {
    color: green[500],
    start: dateObj("2017-2"),
    end: dateObj("2017-9"),
    letter: "N",
    title: "N",
  },
  {
    color: green[500],
    start: dateObj("2017-9"),
    end: dateObj("2022-10"),
    letter: "E",
    title: "E",
  },
  // no blue
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2014-6"),
    end: dateObj("2014-7"),
    letter: "M",
    title: "M",
  },
  {
    color: yellow[500],
    inverted: true,
    start: dateObj("2014-10"),
    end: dateObj("2014-11"),
    letter: "C",
    title: "C",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2015-2"),
    end: dateObj("2015-3"),
    letter: "M",
    title: "M",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2015-3"),
    end: dateObj("2015-4"),
    letter: "K",
    title: "K",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2015-8"),
    end: dateObj("2015-9"),
    letter: "A",
    title: "A",
  },
  {
    color: red[500],
    start: dateObj("2015-8"),
    end: dateObj("2015-9"),
    letter: "A",
    title: "A",
  },
  {
    color: yellow[500],
    inverted: true,
    start: dateObj("2015-9"),
    end: dateObj("2015-12"),
    letter: "V",
    title: "V",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2015-12"),
    end: dateObj("2016-1"),
    letter: "A",
    title: "A",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2016-1"),
    end: dateObj("2016-2"),
    letter: "L",
    title: "L",
  },
  {
    color: red[500],
    start: dateObj("2016-3"),
    end: dateObj("2016-4"),
    letter: "T",
    title: "T",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2016-6"),
    end: dateObj("2016-7"),
    letter: "A",
    title: "A",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2016-7"),
    end: dateObj("2016-8"),
    letter: "Z",
    title: "Z",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2016-7"),
    end: dateObj("2016-9"),
    letter: "S",
    title: "S",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2016-9"),
    end: dateObj("2016-10"),
    letter: "K",
    title: "K",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2016-10"),
    end: dateObj("2016-11"),
    letter: "S",
    title: "S",
  },
  {
    color: orange[500],
    start: dateObj("2017-3"),
    end: dateObj("2017-6"),
    letter: "R",
    title: "R",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2017-5"),
    end: dateObj("2017-6"),
    letter: "GE",
    title: "GE",
  },
  {
    color: yellow[500],
    inverted: true,
    start: dateObj("2017-9"),
    end: dateObj("2017-10"),
    letter: "M",
    title: "M",
  },
  {
    color: grey[50],
    inverted: true,
    start: dateObj("2019-9"),
    end: dateObj("2019-10"),
    letter: "M",
    title: "M",
  },
];

export default letters;
